(cl:in-package #:buoy-simulate)

(defun decode-floatr (floatr)
  (let ((numerator (numerator floatr))
        (denominator (denominator floatr)))
    (let ((numerator-length (integer-length numerator))
          (denominator-length (integer-length denominator)))
      (let* ((difference (- numerator-length denominator-length))
             (shift (1+ difference)))
        (if (minusp difference)
            (setf numerator (ash numerator (- shift)))
            (setf denominator (ash denominator shift)))
        (values (/ numerator denominator) shift)))))
