(cl:in-package #:buoy-core-math-64)

(defun parse-c-literal (literal)
  (let ((x-position (position #\x literal))
        (dot-position (position #\. literal))
        (p-position (position #\p literal)))
    (let* ((sign (if (eql (char literal 0) #\-) -1 1))
           (integer (subseq literal (1+ x-position) dot-position))
           (fraction (subseq literal (1+ dot-position) p-position))
           (exponent (subseq literal (1+ p-position)))
           (digits (concatenate 'string integer fraction)))
      (float (* sign
                (let ((*read-base* 16))
                  (read-from-string digits))
                (expt 2 (- (read-from-string exponent)
                           (* 4 (length fraction)))))
             1d0))))
